# Generated by Django 4.0.4 on 2022-05-10 12:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans', '0002_alter_loans_applicant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loans',
            name='applicant',
        ),
        migrations.AddField(
            model_name='loans',
            name='applicant',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
