# Generated by Django 4.0.4 on 2022-05-10 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans', '0003_remove_loans_applicant_loans_applicant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loans',
            name='applicant',
        ),
        migrations.AddField(
            model_name='loans',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loans',
            name='lender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lender_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
