# Generated by Django 4.0.4 on 2022-05-10 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='bank_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aadhar', models.FileField(null=True, upload_to='Aadhar/')),
                ('Pan', models.FileField(null=True, upload_to='Pan/')),
                ('Salary', models.FileField(null=True, upload_to='Salary/')),
                ('Bank', models.CharField(blank=True, max_length=30, null=True)),
                ('CTC', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
