# Generated by Django 4.0.4 on 2022-05-10 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BankProfile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank_profile',
            name='Bank',
        ),
        migrations.RemoveField(
            model_name='bank_profile',
            name='CTC',
        ),
    ]
