# Generated by Django 4.0.4 on 2022-05-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankProfile', '0002_remove_bank_profile_bank_remove_bank_profile_ctc'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank_profile',
            name='Bank',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bank_profile',
            name='CTC',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
