# Generated by Django 4.0.4 on 2022-05-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankProfile', '0003_bank_profile_bank_bank_profile_ctc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_profile',
            name='Bank',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bank_profile',
            name='CTC',
            field=models.IntegerField(null=True),
        ),
    ]
