# Generated by Django 4.0.4 on 2022-05-11 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankProfile', '0005_bank_profile_cibil_bank_profile_cur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_profile',
            name='CIBIL',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
